### PR TITLE
Module 2

### PR DESCRIPTION
**Pull request by pamalo9**
**SOLUCIÓN MODULE2: EDA**

- Durante este modulo nos hemos centrado en trabajar en entender el tipo de datos que tenemos, resolver los posibles conflictos y realizar un exploratory data analysis.
**comentarios:**
-A aparte de mis análisis propio he añadido la parte de código de la solución propuesta por guille que me ha parecido mas relevante ( Lo he dejado indicado a lo largo del documento).
-Una de las cosas que más me ha costado ha sido entender alguna partes de la solución ya que no entendía como funcionaba parte del código (nunca lo había usado antes).
- No entiendo muy bien la diferencia de cuando es mejor usar seaborn o matplot.

### CODE REVIEW

**Comment by pabaldonedo** [comment]
En cuanto a la pregunta de "matplotlib vs seaborn", ambos son herramientas. La mejor será la que te provea de lo que quieres representar de la mejor forma o más rápida. Seaborn va muy bien cuando tenemos un dataframe y queremos representar dividiendo por grupos con el parámetro "hue", por ejemplo. Otras veces, queremos hacer algo sencillo y rápido o tenemos los datos en listas/numpy arrays diferentes y no en un dataframe único, y con matplotlib conseguimos la representación que queremos más rápido y sencillo.

En definitiva, no te enfoques en la herramienta en sí, sino en "¿qué quiero dibujar?", "¿en qué formato tengo mis datos?", etc. y así podrás elegir qué paquete se adapta mejor a tus necesidades

**Comment by pabaldonedo** [comment]
I know that Guille's solution included this. However, I'd advocate to add this outside the notebook. In fact, you have not added these packages to the PR. `Poetry add` adds the packages to the pyproject.toml file, which must be uploaded to the repo.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-540)._

**Comment by pabaldonedo** [comment]
Get used to document everything in english. That is the real work environment, that's why my reviews are in english too.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-541)._

**Comment by pabaldonedo** [comment]
This is not correct:
 1. The `25%`, `50%` and `75%` are percentiles. So count_peats percentile 75% = 1 means that 75% of the people have AT MOST 1 pet. Actually we know that half of the people has NO pets (percentile 50% is 0). So we should say 75% of people do not have babies and at most have 1 pet.
 2. Important to be explicit, these numbers are out of the people we have data for. So it is "75% of the available data", which is the 75% of 325/4983 of the whole population. We may or may not expect that the whole population will distribute in the same manner. Try always to reflect the assumptions and limitations of each statement.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-542)._

**Comment by pabaldonedo** [comment]
Just small personal comment: colors look better in the [v2.0 palette|https://matplotlib.org/stable/users/prev_whats_new/dflt_style_changes.html], so blue is "C0"

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-543)._

**Comment by pabaldonedo** [comment]
Comments on this plot:
 - Is it relevant to have the exact user id? If not, the xaxis is super clutter at it would be easier to follow with just 1, 2, 3... etc instead the uesr _id
 - Is this plot really relevant? How is this more informative than just the table of value_counts()?
 - the variable says top "10" users, but you are taking the top 50 most frequent values and then the title says "top 100". It is super confusing and error prone. If you want to have the top N probably better to extract it programatically
 - Would not it be more informative to have the histogram of orders per user?

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-544)._

**Comment by pabaldonedo** [comment]
This data comes from the .describe() before, so it should be there and not here

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-545)._

**Comment by pabaldonedo** [comment]
- Conclusion from percentile is wrong again
 - More importantly, the conclusion here is that we have a long tail distribution --> most people has no to little regulars but a handful has many regulars

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-546)._

**Comment by pabaldonedo** [comment]
Try to think of the consequences of what you see and if you can find actionables even better. "There are more regulars in proposition than in top up":
 - How big is this difference?
 - Is this difference expected?
 - How this affects business / modelling?

For example, I have never worked in groceries, for me is surprising that top up (refilling) is not the majority case in the regular item. Maybe it is just ignorance in the field from my side (i should ask the product people), maybe the business is not doing great (business insight) or maybe there is something with the data.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-547)._

**Comment by pabaldonedo** [comment]
If you have a print there is no need to put it in markdown too

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-548)._

**Comment by pabaldonedo** [comment]
- Why you conclude this and not mention in october, the biggest jump?
 - Do we have any hypothesis? Maybe there was a big investment in User Acquisition (UA).
 - Do we need to take any actions? Probably we will expect to have data shifts on January 2021 and on October 2021. This could affect on how we use the data to model.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-549)._

**Comment by pabaldonedo** [comment]
As commented earlier some of this insights are wrong. This is critical. We need to keep working to avoid ending up with misleading information since the most important thing at work is that whatever you do (more or less tasks), you carry it out correctly

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-550)._

**Comment by pabaldonedo** [comment]
I would state clearly that even though you could work without dropping the Nulls for this plot, you are considering that an item without price, vendor, type and tags is probably faulty.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-551)._

**Comment by pabaldonedo** [comment]
Good! But foresee questions, if you state "Most bought products are cleaning related", the immediate question that you will get: "What is its share of the total sales?"

I like that you are given a hypothesis on the superfoods-suplements, trying to think beyond the raw data

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-552)._

**Comment by pabaldonedo** [comment]
I like the idea, but I would challenge the execution. What if it is just a single product within the category what is driving this artificially high? Probably it would have been better to explore the top 75, 90 and maximum prices per category.

In addititon, it would be nice to cross this with popularity, among expensive products, which are the most popular? Because we can have a super expensive product but that was sold only once

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-553)._

**Comment by pabaldonedo** [comment]
Good, may be a table or plot of the distribution of user orders would have been nice, to understand the behaviour of the users that repeat orders. Do they repeat mostly once or they become loyal?

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-554)._

**Comment by pabaldonedo** [comment]
Have a look how in Guille's solution some times this is used. It allows to have several plots and working with `fig, ax` gives you better control on what you are changing within the plot that using directly `plt`

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-555)._

**Comment by pabaldonedo** [comment]
Take a moment to compare these insights with yours above. Not only states what we have observed, but:
 - Gives hypothesis and questions to be answered either by further research / modelling or by asking product (e.g. anchoring, oatly being bought disproportionally)
 - Highlights a point in time where things change (april 2021 -> flat) indicating that the data distribution changes, which is worth noting for modelling

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-556)._

**Comment by pabaldonedo** [comment]
I like this, compute and print relevant and easy to digest data

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-557)._

**Comment by pabaldonedo** [comment]
Good!

Try to digest also the information. Before we saw that for regulars the most relevant product was cleaning and here it is not. So stating the link allow us to create more global and intricate insights.


_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-558)._

**Review by pabaldonedo — COMMENTED** [review]
Me ha gustado que hayas dividido la libreta en secciones con las conclusiones al final de cada una. Quizás lo único tener un resumen general al principio del todo o al final hubiera completado aún más, pero en general está bien.

Una cosa **IMPORTANTÍSIMA** que has de corregir porque ha sido realmente grave. Has malinterpretado percentiles dos veces en el documento. Esto es un error que no puede suceder en ningún caso. Como te puse en la libreta, más que hacer más o menos trabajo lo que se te va a exigir al principio es que lo que hagas lo hagas bien. Este error no sólo invalida ciertas conclusiones es que puede provocar pérdida de confianza en tu trabajo.

También he notado en algún gráfico que parece que no tenías claro exactamente qué buscabas o su finalidad última. Especialmente el gráfico de barras con el top de usuarios por órdenes. Cada gráficos, tabla o análisis ha de tener la finalidad de responder a una pregunta.

Por último, intenta ir más allá de simplemente leer los gráficos/resultados. ¿Qué signfica que hayamos visto X? ¿Qué implica para el negocio? ¿Y para el modelado? ¿Necesito confirmar con producto ciertos comportamientos que no entiendo? Fíjate en los comentarios finales de guille en su libreta, verás que apuntan en esa dirección.

El código, si no has leído [esto](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html) sobre pandas te lo recomiendo para darle un empujón.

¡A seguir trabajando y mejorando en cada PR! ;)

**Comment by pamalo9** [comment]
Done

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-646)._

**Comment by pamalo9** [comment]
Done. Should the comments in the code also be in English (the ones with # in front)?

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-647)._

**Comment by pamalo9** [comment]
Done.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-648)._

**Comment by pamalo9** [comment]
Done.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-649)._

**Comment by pamalo9** [comment]
My bad, I was testing with different values and I forgot to put the same value everywhere. I have created the histogram but Im not sure if It is correct.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-651)._

**Comment by pamalo9** [comment]
Done.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-652)._

**Comment by pamalo9** [comment]
I did not understand these two variables very well, I will take it into account.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-653)._

**Comment by pamalo9** [comment]
Perfect, I just wanted to see initially what form the data would take.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-654)._

**Comment by pamalo9** [comment]
Done. Would one action be to split the data temporally in a linear model?

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-655)._

**Comment by pamalo9** [comment]
Sorry, correct now

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-656)._

**Comment by pamalo9** [comment]
I do not understand this. 

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-657)._

**Comment by pamalo9** [comment]
Perfect, I will do it 

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-658)._

**Comment by pamalo9** [comment]
Done!

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-660)._

**Comment by pamalo9** [comment]
Got it

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-661)._

**Comment by pamalo9** [comment]
sure

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-662)._

**Comment by pamalo9** [comment]
Got it.

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-663)._

**Comment by pamalo9** [comment]
:)

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-664)._

**Comment by pamalo9** [comment]
okay

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-665)._

**Comment by pabaldonedo** [comment]
Yes, everything. Assume that you will be working in an international environment

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-666)._

**Comment by pabaldonedo** [comment]
Most important do you understand what went wrong?

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-667)._

**Comment by pabaldonedo** [comment]
If you do not understand something, first try to figure it out. If unable, ask. Do not hesitate, that is why we have the slack for. Specially, these things that are "Product related". In a real environment you would be able to ask the people from product to get this information

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-668)._

**Comment by pabaldonedo** [comment]
One important thing here. The goal here is not for you to just copy paste my suggested answers into the notebook, but to make you think and even have a discussion. For example, I would still challenge the january statement, I'd love to understand your motivation to make such statement. You have to be used to be challenged. It is super normal that you will be presenting your insights to third parties and these people may challenge them or ask for further details.
In addition, do you have any other hypothesis for the october jump?

Regarding the temporal split, better than asking directly, suggest an action and try to motivate it. This is not like in class where a problem is crafted and there is a "correct" answer the professor knows about. In a real set up you are expected to draw conclusion and propose action and motivate them. Then a senior may challenge them, discard them by bringing new views to the table or suggest new ones. So I would love to hear why would you suggest that action before start a discussion.

Finally, this is not meant to be harsh to any extend, but to try to show you how the day to day in the workplace looks like and the more used you get to that the fastest you will adapt and grow ;)

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-669)._

**Comment by pabaldonedo** [comment]
you are making the plot over `clean_regulars` which is defined as: `clean_regulars = regulars_df.dropna()` This means that any regular that has a Null in any column of the dataset is dropped. However, this plot is just counting the number of users per variant_id, therefore, you could do the plot directly on regulars_df (without dropping Nulls). As long a user_id has a variant_id you can make the counting. However, given the results of the previous cell, we know that some users have NULLs in the columns price, compare_at_price, vendor, product_type and tags.

The question then is: is it reasonable to make this plot dropping the users with nulls in those fields as you have done? OR should you consider them for the plot?

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-670)._

**Comment by pabaldonedo** [comment]
Hi there! I am your chinese colleague what "Precio Máximo" means? ;)

Do not assume that your colleagues can speak spanish, most likely many won't!

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-671)._

**Comment by pabaldonedo** [comment]
- In all categories or only in a handfull? What is "significant"?
- Suggestion, you could do some plots to visualise this better. For example a vertical line with 3 dots: one at p75, other p90 and maximum. Or directly the typical boxplots

_Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-672)._

**Comment by pabaldonedo** [comment]
> My bad, I was testing with different values and I forgot to put the same value everywhere. I have created the histogram but Im not sure if It is correct.
> 
> _Respond and view the context [here](https://gitnotebooks.com/pamalo9/zrive-ds/pull/2#comment-651)._

I do not see this comment in the review notebook, sorry so I do not know what you mean

**Review by pabaldonedo — APPROVED** [review]
Te la dejo aprobada por si quieres hacer merge. Te he dejado algunas preguntas adicionales pero quizás es mejor que te muevas ya al módulo 3.
Lo más importante:

1. ¿Has enteido el error del percentil?
2. Las correciones no las tomes como "haz esto" a no ser que el mensaje sea claramente así. Si son preguntas o hipótesis son para iniciar una discusión o que aclares algo. El objetivo no es hacer copy-paste de mis sugerencias, sino pensar y trabajar sobre ello
3. Has de acostumbrarte a que cualquier afirmación que hagas vaya acompañada de su motivación/argumentación. Es normal que te cuestionen las afirmaciones, se requeiran más detalles o se propongan alternativas.
4. En la vida real rara vez hay respuestas "correctas" como las de un ejercicio en la universidad. Hay un momento donde preguntas "¿habría que hacer temporal split?". Eso en un ejercicio que tiene una "respuesta correcta" es razonable. En una situación real lo suyo es "pasa X e Y, por tanto, propondría hacer temporal split." y si no lo tienes claro se puede añadir "¿alguna objeción?" para un compañero o senior para abrir una discusión. Esto es una situación mucho más real y algo que te va a dar muchos puntos si vas con una propuesta razonada o al menos expones los puntos que te hacen dudar qué acción tomar.


Vamos mejorando de PR en PR, a seguir trabajando y a darle caña al módulo 3 (y al 4!)

**Pull request merged**
